//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employeeNo { get; set; }
        public string employeeName { get; set; }
        public double salary { get; set; }
        public int departmentNo { get; set; }
        public Nullable<System.DateTime> lastModify { get; set; }
    
        public Department Department { get; set; }
    }
}
